// Generates src/components/vendorMarks.generated.ts and src/components/runtimeMarks.generated.ts.
// Sources: Simple Icons (CC0) for anything it carries, plus hand-supplied single-colour paths below.
// Run: node scripts/generate-marks.mjs
import fs from 'node:fs'
import * as si from 'simple-icons'
import bounds from 'svg-path-bounds'
import parsePath from 'parse-svg-path'

const VENDORS = { Intel: 'siIntel', NVIDIA: 'siNvidia', AMD: 'siAmd', Apple: 'siApple' }
const RUNTIMES = { pytorch: 'siPytorch', vllm: 'siVllm', ollama: 'siOllama' }

/** Bake a uniform scale plus translate into a path so it needs no transform attribute. */
function bake(path, { scale = 1, tx = 0, ty = 0 }) {
  const segs = parsePath(path)
  return segs
    .map((seg, i) => {
      const [cmd, ...nums] = seg
      const absolute = cmd === cmd.toUpperCase() || i === 0
      const out = nums.map((n, j) => {
        const isX = j % 2 === 0
        return +(n * scale + (absolute ? (isX ? tx : ty) : 0)).toFixed(3)
      })
      return cmd + out.join(' ')
    })
    .join('')
}

// The first "O" of the OpenVINO wordmark: the ring and its accent, supplied by Horace on Sep 2, 2026.
const OPENVINO_O = [
  bake(
    'm95.938 147.706c8.945 0 16.417 3 22.417 9s9 13.444 9 22.333-3 16.333-9 22.333-13.472 9-22.417 9c-8.944 0-16.402-2.986-22.375-8.958-5.972-5.972-8.958-13.43-8.958-22.375 0-8.889 2.972-16.333 8.917-22.333 5.944-6 13.416-9 22.416-9zm-21.75 31.333c0 6.222 2.111 11.5 6.334 15.833 4.222 4.334 9.361 6.5 15.416 6.5 6.111 0 11.278-2.138 15.5-6.416 4.223-4.278 6.334-9.584 6.334-15.917 0-6.222-2.111-11.5-6.334-15.833-4.222-4.334-9.389-6.5-15.5-6.5s-11.264 2.153-15.458 6.458c-4.194 4.306-6.292 9.597-6.292 15.875z',
    { scale: 1.11749, tx: -71.60878, ty: -164.34418 },
  ),
  bake(
    'm67.795 88.342c.599 1.614 .926 3.36 .926 5.181 0 8.232-6.683 14.914-14.914 14.914s-14.914-6.682-14.914-14.914c0-8.231 6.683-14.914 14.914-14.914 1.821 0 3.567.327 5.181.926-1.854 1.125-3.094 3.163-3.094 5.488 0 3.54 2.874 6.413 6.414 6.413 2.325 0 4.362-1.239 5.487-3.094z',
    { tx: -19.16058, ty: -57.39018 },
  ),
]

// Hand-supplied marks: { title, path }. Paths must be single-colour; transforms are baked in above.
const CUSTOM_RUNTIMES = {
  'openvino-genai': { title: 'OpenVINO GenAI', paths: [{ d: OPENVINO_O[0], fill: 'currentColor' }, { d: OPENVINO_O[1], fill: '#6c04f4' }], box: '0 0 72 88' },
  // llama.cpp mark, supplied by Horace on Sep 2, 2026 from the llama.cpp project (MIT). Drawn near-black in the original.
  llamacpp: {
    title: 'llama.cpp',
    paths: [{ d: 'M600 392L504.249 558L504.137 557.929C487.252 584.069 458.193 600 426.864 600H120L240 392H600Z M240 392H0L199.602 46.0254C216.032 17.5463 246.411 3.25756e-05 279.29 0H466.154L240 392Z', fill: 'currentColor' }],
    box: '0 0 600 600',
  },
}

/** Near-black brand colours become currentColor, which the components resolve to the foreground on the dark ground. */
function brandFill(hex) {
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255)
  const lum = 0.2126 * r + 0.7152 * g + 0.0722 * b
  return lum < 0.2 ? 'currentColor' : '#' + hex.toLowerCase()
}

function entry(title, paths, fallbackBox = '0 0 24 24') {
  const all = paths.map((p) => p.d).join(' ')
  try {
    const [x0, y0, x1, y1] = bounds(all)
    const w = x1 - x0, h = y1 - y0
    return { title, viewBox: `${x0.toFixed(3)} ${y0.toFixed(3)} ${w.toFixed(3)} ${h.toFixed(3)}`, ratio: +(w / h).toFixed(3), paths }
  } catch {
    console.warn(`${title}: path parser rejected it, using ${fallbackBox}`)
    const [, , w, h] = fallbackBox.split(' ').map(Number)
    return { title, viewBox: fallbackBox, ratio: +(w / h).toFixed(3), paths }
  }
}
const fromSimple = (key) => entry(si[key].title, [{ d: si[key].path, fill: brandFill(si[key].hex) }])

const vendors = Object.fromEntries(Object.entries(VENDORS).map(([k, key]) => [k, fromSimple(key)]))
const runtimes = {
  ...Object.fromEntries(Object.entries(RUNTIMES).map(([k, key]) => [k, fromSimple(key)])),
  ...Object.fromEntries(Object.entries(CUSTOM_RUNTIMES).map(([k, v]) => [k, entry(v.title, v.paths, v.box)])),
}

const header = (what) => `// Generated by scripts/generate-marks.mjs. Do not edit by hand.\n// ${what}\n`
fs.writeFileSync('src/components/vendorMarks.generated.ts', header('Vendor wordmarks from Simple Icons (CC0) in their brand colours, tight boxes so each keeps its own proportions.') + `export const VENDOR_MARKS: Record<string, { title: string; viewBox: string; ratio: number; paths: { d: string; fill: string }[] }> = ${JSON.stringify(vendors, null, 2)}\n`)
fs.writeFileSync('src/components/runtimeMarks.generated.ts', header("Runtime marks: Simple Icons (CC0) plus hand-supplied paths. Cascadia's mark is a file under /logos/runtimes.") + `export const RUNTIME_MARKS: Record<string, { title: string; viewBox: string; ratio: number; paths: { d: string; fill: string }[] }> = ${JSON.stringify(runtimes, null, 2)}\n`)
for (const [k, v] of Object.entries({ ...vendors, ...runtimes })) console.log(k.padEnd(10), 'ratio', v.ratio)
